# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ttylag < Formula
  desc "Userspace PTY wrapper that simulates laggy/slow network connections"
  homepage "https://github.com/cbrunnkvist/ttylag"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cbrunnkvist/ttylag/releases/download/0.1.5/ttylag_Darwin_x86_64.tar.gz"
      sha256 "8cfabd8b9758a9bdf614871215489af683a53217861eff48bb4a1d13689b5767"

      def install
        bin.install "ttylag"
        man1.install "ttylag.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cbrunnkvist/ttylag/releases/download/0.1.5/ttylag_Darwin_arm64.tar.gz"
      sha256 "dbe300d55c656188582cc7af7063aa41372fceea005ba7d8e3727082d26b552d"

      def install
        bin.install "ttylag"
        man1.install "ttylag.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cbrunnkvist/ttylag/releases/download/0.1.5/ttylag_Linux_x86_64.tar.gz"
      sha256 "1a0edb29318c7cebd32e882867c3d7879d52f40c95dda7c35c9eedd2c05d04c6"
      def install
        bin.install "ttylag"
        man1.install "ttylag.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cbrunnkvist/ttylag/releases/download/0.1.5/ttylag_Linux_arm64.tar.gz"
      sha256 "6dd79e59395d4f669cf40f49aafe82027ec0505eafc315067a2dc21dc28e6573"
      def install
        bin.install "ttylag"
        man1.install "ttylag.1"
      end
    end
  end

  test do
    system "#{bin}/ttylag", "--version"
  end
end
