# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ttylag < Formula
  desc "Userspace PTY wrapper that simulates laggy/slow network connections"
  homepage "https://github.com/cbrunnkvist/ttylag"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cbrunnkvist/ttylag/releases/download/0.1.3/ttylag_Darwin_x86_64.tar.gz"
      sha256 "c2a9060dd7e8e0b2b2302646cf46c5a8c278339550ea38620009f33a6636b168"

      def install
        system "go", "build", *std_go_args(ldflags: "-s -w")
        system "go", "run", "cmd/genman/main.go", "-o", "ttylag.1"
        man1.install "ttylag.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cbrunnkvist/ttylag/releases/download/0.1.3/ttylag_Darwin_arm64.tar.gz"
      sha256 "9910af5ed75ccb20450677fbd4ab22ec18f571320053e58078836036b88b3d8a"

      def install
        system "go", "build", *std_go_args(ldflags: "-s -w")
        system "go", "run", "cmd/genman/main.go", "-o", "ttylag.1"
        man1.install "ttylag.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cbrunnkvist/ttylag/releases/download/0.1.3/ttylag_Linux_x86_64.tar.gz"
      sha256 "79dc69bd7f7896991724bf6a6746b85d8e55861c0ba16db72e1c640145f33f4f"
      def install
        system "go", "build", *std_go_args(ldflags: "-s -w")
        system "go", "run", "cmd/genman/main.go", "-o", "ttylag.1"
        man1.install "ttylag.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cbrunnkvist/ttylag/releases/download/0.1.3/ttylag_Linux_arm64.tar.gz"
      sha256 "a70ead72cc44c1c9a0b57d492a8591f296ce2714715d9468d79b21ebafdd9d9f"
      def install
        system "go", "build", *std_go_args(ldflags: "-s -w")
        system "go", "run", "cmd/genman/main.go", "-o", "ttylag.1"
        man1.install "ttylag.1"
      end
    end
  end

  test do
    system "#{bin}/ttylag", "--version"
  end
end
