# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ttylag < Formula
  desc "Userspace PTY wrapper that simulates laggy/slow network connections"
  homepage "https://github.com/cbrunnkvist/ttylag"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cbrunnkvist/ttylag/releases/download/0.1.4/ttylag_Darwin_x86_64.tar.gz"
      sha256 "e02385272c46b89cfe4027b3b97fffbf21a69c2ff39b9dc9f7bdbd87cc576322"

      def install
        bin.install "ttylag"
        man1.install "ttylag.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cbrunnkvist/ttylag/releases/download/0.1.4/ttylag_Darwin_arm64.tar.gz"
      sha256 "c2380da1889c66d82cf9e2fb26805a4c70676a32dfcffc9a2b225ea025802e15"

      def install
        bin.install "ttylag"
        man1.install "ttylag.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cbrunnkvist/ttylag/releases/download/0.1.4/ttylag_Linux_x86_64.tar.gz"
      sha256 "a191f84bf386f6ed2d6a20f32c215d013116d32f9ae3d101a5077e9a43ffce85"
      def install
        bin.install "ttylag"
        man1.install "ttylag.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cbrunnkvist/ttylag/releases/download/0.1.4/ttylag_Linux_arm64.tar.gz"
      sha256 "0f8e7eadbb9aa93c6df1b1f9691a54f738f9e137661473ad44a415d769c92c50"
      def install
        bin.install "ttylag"
        man1.install "ttylag.1"
      end
    end
  end

  test do
    system "#{bin}/ttylag", "--version"
  end
end
